name: Terraform CI

on:
  push:
    branches:
      - prod
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3,lambda,dynamodb,apigateway,iam
          DEBUG: 1

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug directories
        run: |
          pwd
          ls -la
          ls -la Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Wait for LocalStack
        run: sleep 10

      - name: Terraform Init
        run: |
          cd Terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd Terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd Terraform
          terraform plan