name: Terraform CI

on:
  push:
    branches:
      - prod
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3,lambda,dynamodb,apigateway,iam
          DEBUG: 1

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show directory structure
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Wait for LocalStack
        run: sleep 10

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: Terraform
        run: terraform plan