name: Terraform CI

on:
  push:
    branches:
      - prod
      - main

jobs:

  terraform:

    runs-on: ubuntu-latest

    services:

      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3,lambda,dynamodb,apigateway,iam

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Wait for LocalStack
        run: sleep 10

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      
